Dataset Califórnia para regressão

In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

# Carregar o dataset California Housing
housing = fetch_california_housing()
X = pd.DataFrame(housing.data, columns=housing.feature_names)
y = pd.Series(housing.target, name='MedHouseVal')

# Dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

display(X.head())
display(y.head())

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

Testando diferentes algoritmo de regressão

In [ ]:
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor

# Testando diferentes algoritmos de regressão

# Regressão Linear
model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
r2 = model_lr.score(X_test, y_test)
print(f"Performance do modelo: {r2:.2f}")

# Regressão Ridge
model_ridge = Ridge(alpha=1.0)
model_ridge.fit(X_train, y_train)
r2 = model_ridge.score(X_test, y_test)
print(f"Performance do modelo: {r2:.2f}")

# Regressão com Random Forest
model_rf = RandomForestRegressor()
model_rf.fit(X_train, y_train)
r2 = model_rf.score(X_test, y_test)
print(f"Performance do modelo: {r2:.2f}")

Performance do modelo: 0.60
Performance do modelo: 0.60
Performance do modelo: 0.81